apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-app
  namespace: handson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: local-app
    spec:
      containers:
      - name: app
        image: centos
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: local-claim
status: {}