kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv1g
  namespace: handson
spec:
  storageClassName: local-sc
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp
