apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: handson
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1> This is a Configmap Index html </h1>
    </html>