apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: handson-role
  namespace: handson
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - create
  - update
