apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: handson2-network-policy
  namespace: handson2
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - {}