apiVersion: apps/v1
kind: Deployment
metadata:
  name: handson-db
  namespace: handson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: handson-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: handson-db
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: handson
          image: mariadb
          name: handson-db
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: handson-db-vol
      restartPolicy: Always
      volumes:
        - name: handson-db-vol
          persistentVolumeClaim:
            claimName: handson-db
status: {}