apiVersion: v1
kind: Service
metadata:
  labels:
    app: handson-db
  name: handson-db
spec:
  ports:
    - name: "mariadb"
      port: 3306
      targetPort: 3306
  selector:
    app: handson-db
  type: LoadBalancer
status:
  loadBalancer: {}