apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stress
  name: stress
  namespace: handson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - image: vish/stress
        name: stress
        resources: 
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "200Mi"
        args:
        - -cpus
        - "2"
        - -mem-total
        - "1950Mi"
        - -mem-alloc-size
        - "100Mi"
        - -mem-alloc-sleep
        - "1s"
      restartPolicy: Always
status: {}